### ISSUE TITLE
Эскизы предварительного просмотра

### ISSUE THREAD

**Issue by motoprogger** [trolley813/ArchiBase#4]
**Связан ли ваш запрос с проблемой? Опишите, пожалуйста.**
На главной странице и на страницах со списком фотографий сами фотографии иногда (видимо, в зависимости от нагрузки на сервер) загружаются очень долго. Как выяснилось, они загружаются с сервера в полном размере, а затем масштабируются браузером. С ростом числа пользователей данное обстоятельство будет создавать избыточную нагрузку на дисковый ввод-вывод сервера и его подключение к Интернету.

**Опишите решение, которое вы хотели бы**
Предлагаю сформировать заранее эскизы предварительного просмотра (размером, например, 240x180) и на страницах со списком фотографий отображать их.

**Comment by trolley813** [comment]
Сделано, появится в версии 0.2.3. Миниатюры будут в формате WEBP максимальным разрешением 240x180. По размеру в большинстве случаев это 15-20 KB (редко до 30), поэтому лежать это все будет прямо в базе, так будет наверняка быстрее, чем файлами.

**Comment by motoprogger** [comment]
Версия 0.2.3, как я вижу, внедрена на сайте, но картинки по-прежнему загружаются в полном размере

**Comment by trolley813** [comment]
Да, сейчас оно там есть только на части страниц (поскольку внедрялось в тестовом режиме): например, списки всех фото (/photos) и фото на странице здания (/buildings/<id>) отображают миниатюры. С версии 0.2.4 появится уже на всех страницах, где это требуется (например, главная, галереи, страницы городов и регионов). Исправление уже готово, сама версия будет выпущена ориентировочно до конца недели.

**Comment by motoprogger** [comment]
Вижу. Только на главной странице эскизы зачем-то крупнее, чем в остальных местах (300x200 вместо 240x160). Сами изображения при этом загружаются 240x160 и масштабируются браузером.

**Comment by trolley813** [comment]
Исправлено в версии 0.2.7.

**Comment by motoprogger** [comment]
Вижу исправление
