### ISSUE TITLE
Предложения по улучшению "Большой карты"

### ISSUE THREAD

**Issue by motoprogger** [trolley813/ArchiBase#5]
**Связан ли ваш запрос с проблемой? Опишите, пожалуйста.**
В настоящее время на "Большой карте" отображаются только номера домов. Это создаёт неудобства при поиске нужного здания: нужно каждый подходящий номер открыть и посмотреть, к какой улице он относится.

**Опишите решение, которое вы хотели бы**
1) В мелком масштабе не показывать ярлычки зданий, а группировать их в иконки, показывающие, сколько зданий представляет каждая из них, так, чтобы сохранить читаемость карты
2) Добавить к каждому ярлычку здания всплывающую подсказку со всеми адресами соответствующего здания

**Comment by trolley813** [comment]
Новая карта на Leaflet с группировкой и подсказками в процессе разработки, тоже будет в версии 0.2.3.

**Comment by motoprogger** [comment]
Вижу, появилось
