### ISSUE TITLE
Ошибка при загрузке более одной фотографии

### ISSUE THREAD

**Issue by motoprogger** [trolley813/ArchiBase#6]
**Описание ошибки** 
Из формы загрузки фотографий невозможно загрузить более одной фотографии, не перезагружая страницу 

**Чтобы воспроизвести** 
Шаги для воспроизведения поведения: 
Выбрать в меню в левой части главной страницы "Photos" -> "Upload photo"
На открывшейся странице выбрать файл для загрузки, заполнить требуемые поля и нажать "Upload"
В правой части окна отобразится сообщение об успешной загрузке.
После этого выбрать другой файл, внести данные о нём и нажать "Upload"

**Ожидаемое поведение** 
1) Отобразится сообщение об успешной загрузке
2) В "Журнале" появится фотография, ожидающая публикации

**Скриншоты** 
Сообщение об ошибке: https://ibb.co/4KRXMDd 

**Компьютер (заполните следующую информацию):** 
- OS: Debian 12.6 (x64)
- Браузер: Pale Moon 33.4.0 (64-bit) (GTK2)

**Дополнительный контекст**
На фрагменте скриншота видны также проблемы с отображением значков, они в этом браузере постоянные. Однако, судя по тексту ошибки, а также по тому, что первая фотография загружается, ошибка связана со внутренней логикой движка, а не с обработкой в браузере.

**Comment by trolley813** [comment]
В версии 0.2.3 будет сброс переменных состояния (некоторых) после загрузки, это должно помочь решить проблему.
