### ISSUE TITLE
Отображение зданий без фотографий

### ISSUE THREAD

**Issue by motoprogger** [trolley813/ArchiBase#8]
**Описание ошибки** 
На "большой карте" ярлычки всех зданий имеют оранжевый цвет текста, который должен указывать, что у здания нет фотографий

**Чтобы воспроизвести** 
Шаги для воспроизведения поведения: 
1. Открыть "Большую карту" любого города, далее в примерах Кирово-Чепецк https://domofoto.melnix.ru/locations/1a8a698b-5562-46d6-9ba8-3fcfcdec7fbc

**Ожидаемое поведение** 
Действующие здания, имеющие фотографии, отображаются чёрными ярлычками с белым текстом. Действующие здания, не имеющие фотографий, отображаются чёрными ярлычками с оранжевым текстом.
https://domofoto.melnix.ru/buildings/0d21cd3e-e1d2-473e-9125-8d7e9f2f986f - должно быть с белым текстом
https://domofoto.melnix.ru/buildings/5f4def09-6419-4c95-925d-2a04fd8cef15 - верно отображается оранжевым

**Скриншоты** 
https://ibb.co/QQPTDk0

**Компьютер (заполните следующую информацию):** 
- ОС: Debian 12.6
- Браузер Pale Moon 33.4.0 (64-bit) (GTK2)

**Comment by trolley813** [comment]
Исправлено, появится в версии 0.2.6.

**Comment by motoprogger** [comment]
Проверил на нескольких городах, работает
