### ISSUE TITLE
Невозможно выбрать конкретное здание на форме загрузке фотографии

### ISSUE THREAD

**Issue by motoprogger** [trolley813/ArchiBase#9]
**Описание ошибки** 
При вводе некоторых вариантов текста в поле "Привязать здание" отображается сообщение об ошибке "An unhandled error has occurred", и пользовательский интерфейс перестаёт отвечать. В частности, такая ситуация была связана с загрузкой фотографии для здания: https://domofoto.melnix.ru/buildings/9754cac3-7d17-4e4a-bfa0-26573c00b04c

**Чтобы воспроизвести** 
Шаги для воспроизведения поведения: 
1. На главной странице в меню слева выбрать "Photos -> Upload"
2. В рамке "Buildings" в поле "Select a location" ввести "Омск" и в раскрывающемся списке выбрать г. Омск (https://domofoto.melnix.ru/locations/08887b0e-dea0-47c9-aac6-2e3282854a91)
3) Нажать кнопку "Bind a building"
4) В поле поиска здания ввести текст "11"

**Ожидаемое поведение** 
1) В списке под полем поиска отобразится список зданий, в котором будет пункт "11-я Ремесленная улица, 25с"
2) После выбора этого пункта в списке привязок загружаемой фотографии появится здание https://domofoto.melnix.ru/buildings/9754cac3-7d17-4e4a-bfa0-26573c00b04c

**Скриншоты**
https://ibb.co/F3wQyW6

**Компьютер (заполните следующую информацию):** 
- ОС: Debian 12.6
- Браузер: Firefox 115.12.0esr (64-bit) 
- Версия: 0.2.7.0

**Comment by trolley813** [comment]
Вроде бы исправлено в 0.2.8. Пришлось вернуться к загрузке всех зданий города в память вместо подгрузки по мере необходимости (из-за этого и падало). Потребление памяти увеличилось, конечно, но вроде как эта память высвобождается.

**Comment by trolley813** [comment]
Версия 0.2.8 на сайте. Проверил, загрузил пару фото, вроде бы все в порядке.
